name: Debug

on:
  workflow_dispatch: {}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4

      - name: Clean old run log
        id: clean_old_run
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GITHUB_API_URL: https://api.github.com
        run: |
          export
          API_URL=${GITHUB_API_URL:-"https://api.github.com"}
          WORKFLOW_ID=$(gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows" | jq -r ".workflows[] | select(.name == \"${GITHUB_WORKFLOW}\") | .id")

          gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
            | jq -r --arg CURRENT_RUN_ID "$GITHUB_RUN_ID" '.workflow_runs[] | select(.id != ($CURRENT_RUN_ID | tonumber) and (.status == "in_progress" or .status == "queued")) | .id' \
            | while read -r RUN_ID; do
                echo "Cancelling workflow run ID: $RUN_ID"
                if gh api -X POST "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}/cancel"; then
                  echo "Successfully cancelled workflow run ID: $RUN_ID"
                else
                  echo "Failed to cancel workflow run ID: $RUN_ID"
                fi
            done

          gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
            | jq -r --arg CURRENT_RUN_ID "$GITHUB_RUN_ID" '.workflow_runs[] | select(.id != ($CURRENT_RUN_ID | tonumber)) | .id' \
            | while read -r RUN_ID; do
                echo "Deleting workflow run ID: $RUN_ID"
                gh api -X DELETE "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}" && \
                echo "Deleted $RUN_ID" || echo "Failed to delete $RUN_ID"
            done

      # - name: Clean up disk
      #   id: clean_disk
      #   run: |
      #     docker run -v /:/host_machine bash -c "rm -rf /host_machine/opt/hostedtoolcache /host_machine/usr/local/lib/android /host_machine/usr/local/share/powershell"

      # - name: Check have running workflow
      #   id: check_running_workflow
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      #     GITHUB_API_URL: https://api.github.com
      #     WORKFLOW_NAME: Deploy
      #   run: |
      #     API_URL=${GITHUB_API_URL:-"https://api.github.com"}
      #     WORKFLOW_ID=$(gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows" | jq -r ".workflows[] | select(.name == \"${WORKFLOW_NAME}\") | .id")

      #     gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" | jq -e '.workflow_runs[] | select(.status == "in_progress")' >/dev/null && echo "Running workflows detected. Exiting." && exit 1 || echo "No running workflows found."
      #     gh api -X POST "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_NAME}.yaml/dispatches" -F ref=main

      - name: Clean offline runners
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GITHUB_API_URL: https://api.github.com
        run: |
          # Replace with your repository details
          OWNER="nor1hc"
          REPO="private-repo"

          # List all runners
          RUNNERS=$(gh api -H "Accept: application/vnd.github+json" \
            /repos/$OWNER/$REPO/actions/runners | jq -r '.runners[] | @base64')

          # Loop through each runner
          for RUNNER in $RUNNERS; do
            # Decode runner details
            RUNNER_DATA=$(echo "$RUNNER" | base64 --decode)
            
            # Extract runner ID and status
            RUNNER_ID=$(echo "$RUNNER_DATA" | jq -r '.id')
            RUNNER_NAME=$(echo "$RUNNER_DATA" | jq -r '.name')
            RUNNER_STATUS=$(echo "$RUNNER_DATA" | jq -r '.status')

            # Check if the runner is offline
            if [[ "$RUNNER_STATUS" == "offline" ]]; then
              echo "Deleting offline runner: $RUNNER_NAME (ID: $RUNNER_ID)"
              
              # Delete the runner
              gh api -X DELETE -H "Accept: application/vnd.github+json" \
                /repos/$OWNER/$REPO/actions/runners/$RUNNER_ID
              
              echo "Deleted runner: $RUNNER_NAME (ID: $RUNNER_ID)"
            fi
          done
