name: Debug

on:
  workflow_dispatch: {}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clean old run log
        id: clean_old_run
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GITHUB_API_URL: https://api.github.com
        run: |
          # Set the base API URL for GitHub or Enterprise GitHub
          API_URL=${GITHUB_API_URL:-"https://api.github.com"}

          # Get the Workflow ID
          WORKFLOW_ID=$(gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows" | jq -r ".workflows[] | select(.name == \"${GITHUB_WORKFLOW}\") | .id")

          # Check if WORKFLOW_ID is empty
          if [[ -z "$WORKFLOW_ID" ]]; then
            echo "Error: Workflow ID not found for workflow name ${GITHUB_WORKFLOW}"
            exit 1
          fi

          # Fetch Workflow Runs
          RUNS_JSON=$(gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" || echo "")

          # Check if RUNS_JSON is empty
          if [[ -z "$RUNS_JSON" ]]; then
            echo "Error: No workflow runs found or failed to fetch runs"
            exit 1
          fi

          # Process and clean up workflow runs
          echo "$RUNS_JSON" \
            | jq -r '.workflow_runs[]? | {id: .id, status: .status}' \
            | while read -r RUN; do
                RUN_ID=$(echo "$RUN" | jq -r '.id')
                STATUS=$(echo "$RUN" | jq -r '.status')

                # Cancel running workflows if CANCEL_RUN is true
                if [[ "$STATUS" == "in_progress" && "${CANCEL_RUN}" == "true" ]]; then
                    echo "Canceling workflow run ID: $RUN_ID"
                    if gh api -X POST "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}/cancel"; then
                        echo "Successfully canceled workflow run ID: $RUN_ID"
                    else
                        echo "Failed to cancel workflow run ID: $RUN_ID"
                        continue
                    fi
                fi

                # Delete the workflow run
                echo "Deleting workflow run ID: $RUN_ID (Status: $STATUS)"
                if gh api -X DELETE "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}"; then
                    echo "Deleted workflow run ID: $RUN_ID"
                else
                    echo "Failed to delete workflow run ID: $RUN_ID"
                fi
            done


      - name: Clean up disk
        id: clean_disk
        run: |
          docker run -v /:/host_machine bash -c "rm -rf /host_machine/opt/hostedtoolcache /host_machine/usr/local/lib/android /host_machine/usr/local/share/powershell"
