name: Debug

on:
  workflow_dispatch: {}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          gh workflow list
          # Fetch the workflow ID using GitHub CLI
          WORKFLOW_ID=$(gh api "/repos/${GITHUB_REPOSITORY}/actions/workflows" \
            | jq -r ".workflows[] | select(.name == \"${GITHUB_WORKFLOW}\") | .id")

          gh api "/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
            | jq -c '.workflow_runs[] | select(.status != "in_progress" and .status != "queued") | {id: .id, status: .status, conclusion: .conclusion}' \
            | while read -r RUN; do
                RUN_ID=$(echo "$RUN" | jq -r '.id')
                STATUS=$(echo "$RUN" | jq -r '.status')
                CONCLUSION=$(echo "$RUN" | jq -r '.conclusion')

                # Delete completed workflow runs
                echo "Deleting workflow run ID: $RUN_ID (Status: $STATUS, Conclusion: $CONCLUSION)"
                if gh api -X DELETE "/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}"; then
                  echo "Successfully deleted workflow run ID: $RUN_ID"
                else
                  echo "Failed to delete workflow run ID: $RUN_ID"
                fi
            done