name: Debug

on:
  workflow_dispatch: {}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clean old run log
        id: clean_old_run
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GITHUB_API_URL: https://api.github.com
        run: |
          API_URL=${GITHUB_API_URL:-"https://api.github.com"}
          WORKFLOW_ID=$(gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows" | jq -r ".workflows[] | select(.name == \"${GITHUB_WORKFLOW}\") | .id")
          gh api "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_ID}/runs" \
            | jq -r '.workflow_runs[] | select(.status != "in_progress" and .status != "queued") | .id' \
            | while read -r RUN_ID; do
                echo "Deleting workflow run ID: $RUN_ID"
                gh api -X DELETE "${API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${RUN_ID}" && \
                echo "Deleted $RUN_ID" || echo "Failed to delete $RUN_ID"
            done

      - name: Clean up disk
        id: clean_disk
        run: |
          docker run -v /:/host_machine bash -c "rm -rf /host_machine/opt/hostedtoolcache /host_machine/usr/local/lib/android /host_machine/usr/local/share/powershell"
