name: Debug

on:
  workflow_dispatch: {}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug
        run: |
          docker --version
          gh workflow list
